#!/usr/bin/env bash
# script that transfers a file from our client to a server:

ARGS=4
if [ $# -lt "$ARGS" ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 0
fi

scp -i "$4" "$1" "$3"@"$2":~/
