#!/usr/bin/env bash
# script that creates an nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start