#!/usr/bin/env bash
# script that creates an nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start