#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.

if (($1 == ''))
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for i in {1..100}
    do
        ping $1
    done
fi
