#!/usr/bin/env bash
# Script that display 10 times "Holberton School"

i=1
while [ "$i" -le "20" ]
do
    select i
    do
	case $i in
            4)
		echo "Exiting."
		break
		;;
            *)
		echo "You picked $FILENAME ($REPLY)"
		chmod go-rwx "$FILENAME"
		;;
	esac
    done

    select i
    do  done 

    if [[ $i == 3 ]]
    then
	echo "bad luck from China"
    elif [[ $i == 7 ]]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
